var gwtGameList=[
 {"provider":"gwt",type:"Slot","gameId":"cs","title":"Captain Shark"},
{"provider":"gwt",type:"Slot","gameId":"fb","title":"Fire Bird"},
{"provider":"gwt",type:"Slot","gameId":"cdt","title":"Corida de Toros"},
{"provider":"gwt",type:"Slot","gameId":"cc81","title":"Criss Cross 81"},
{"provider":"gwt",type:"Slot","gameId":"fp","title":"Fenix Play"},
{"provider":"gwt",type:"Slot","gameId":"fp27","title":"Fenix Play 27"},
{"provider":"gwt",type:"Slot","gameId":"bph","title":"Beach Party Hot"},
{"provider":"gwt",type:"Slot","gameId":"hp","title":"Hot Party"},
{"provider":"gwt",type:"Slot","gameId":"mf","title":"Magic Fruits"},
{"provider":"gwt",type:"Slot","gameId":"mf27","title":"Magic Fruits 27"},
{"provider":"gwt",type:"Slot","gameId":"mf4","title":"Magic Fruits 4", imgext:"mf4.png"},
{"provider":"gwt",type:"Slot","gameId":"mf81","title":"Magic Fruits 81"},
{"provider":"gwt",type:"Slot","gameId":"mh","title":"Magic Hot"},
{"provider":"gwt",type:"Slot","gameId":"mh4","title":"Magic Hot 4"},
{"provider":"gwt",type:"Slot","gameId":"mj81","title":"Mega Jack 81"},
{"provider":"gwt",type:"Slot","gameId":"mt","title":"Magic Target"},
{"provider":"gwt",type:"Slot","gameId":"vh","title":"Vegas Hot"},
{"provider":"gwt",type:"Slot","gameId":"sh","title":"Super Hot"},
{"provider":"gwt",type:"Slot","gameId":"lq","title":"Lucky Queen"},
{"provider":"gwt",type:"Slot","gameId":"nc81","title":"Night Club 81"},
{"provider":"gwt",type:"Slot","gameId":"motr","title":"Magic Of The Ring"},
{"provider":"gwt",type:"Slot","gameId":"bom","title":"Book of Magic"},
{"provider":"gwt",type:"Slot","gameId":"fbm","title":"Football Mania"},
{"provider":"gwt",type:"Slot","gameId":"fm","title":"Fruit Mania"},
{"provider":"gwt",type:"Slot","gameId":"hth","title":"Highway To Hell"},
{"provider":"gwt",type:"Slot","gameId":"tm","title":"Tetri Mania"},
{"provider":"gwt",type:"Slot","gameId":"h777","title":"Hot 777", imgext:"hot777.jpg"},
{"provider":"gwt",type:"Slot","gameId":"bhs","title":"Black Horse", imgext:"bh.jpg"},
{"provider":"gwt",type:"Slot","gameId":"bw","title":"Bell Wizard"},
{"provider":"gwt",type:"Slot","gameId":"gl40","title":"Good Luck 40"},
{"provider":"gwt",type:"Slot","gameId":"myj","title":"Mystery Jack"},
{"provider":"gwt",type:"Casual Game","gameId":"eb","title":"Extra Bingo"},
{"provider":"gwt",type:"Slot","gameId":"ts","title":"Triple Star", imgext:"ts.png"},
{"provider":"gwt",type:"Slot","gameId":"tot","title":"Ten or Twenty"},
{"provider":"gwt",type:"Slot","gameId":"mbe","title":"Miami Beach"},
{"provider":"gwt",type:"Slot","gameId":"bs","title":"Burning Stars"},
{"provider":"gwt",type:"Slot","gameId":"ss","title":"Sizzling Stars", imgext:"sizzling_stars.jpg"},
{"provider":"gwt",type:"Slot","gameId":"bh","title":"Black Hawk", imgext:"blackhawk.jpg"},
{"provider":"gwt",type:"Slot","gameId":"je","title":"Joker Explosion"},
{"provider":"gwt",type:"Slot","gameId":"gs","title":"Golden Sphinx"},
{"provider":"gwt",type:"Slot","gameId":"wg","title":"Wild Girls"},
{"provider":"gwt",type:"Slot","gameId":"tp","title":"Turbo Play"},
{"provider":"gwt",type:"Slot","gameId":"lf","title":"Lucky Fortune"},
{"provider":"gwt",type:"Slot","gameId":"mj","title":"Mega Jack", imgext:"megajack.jpg"},
{"provider":"gwt",type:"Slot","gameId":"ms","title":"Magic Stars", imgext:"magic_stars.jpg"},
{"provider":"gwt",type:"Slot","gameId":"vr2","title":"Vegas Reels II"},
{"provider":"gwt",type:"Poker","gameId":"ap5","title":"American Poker V", imgext:"apv.jpg"},
{"provider":"gwt",type:"Poker","gameId":"jp","title":"Joker Poker", imgext:"jokerpoker.jpg"},
{"provider":"gwt",type:"Slot","gameId":"bp","title":"Beach Party"},
{"provider":"gwt",type:"Slot","gameId":"war","title":"Win & Replay"},
{"provider":"gwt",type:"Slot","gameId":"lt","title":"Lost Treasure"},
{"provider":"gwt",type:"Slot","gameId":"ar","title":"Arcade"},
{"provider":"gwt",type:"Poker","gameId":"tc","title":"Three Cards", imgext:"threecards.jpg"},
{"provider":"gwt",type:"Poker","gameId":"tpo","title":"Turbo Poker", imgext:"turbopoker.jpg"},
{"provider":"gwt",type:"Poker","gameId":"mp","title":"Magic Poker", imgext:"magicpoker.jpg"},
{"provider":"gwt",type:"Poker","gameId":"agp","title":"American Gold Poker"},
{"provider":"gwt",type:"Slot","gameId":"dj27","title":"Demon Jack 27", imgext:"dj27_icon.jpg"},
{"provider":"gwt",type:"Slot","gameId":"joh","title":"Jack on Hold"},
{"provider":"gwt",type:"Table","gameId":"rg","title":"Gold Roulette"},
{"provider":"gwt",type:"Table","gameId":"cr","title":"Casino Roulette"},
{"provider":"gwt",type:"Slot","gameId":"vh81","title":"Vegas Hot 81", imgext:"vh81_icon.png"},
{"provider":"gwt",type:"Slot","gameId":"cc","title":"Crazy Cars"},
{"provider":"gwt",type:"Slot","gameId":"wth81","title":"Welcome To Hell 81", imgext:"wth81_icon.png"},
{"provider":"gwt",type:"Casual Game","gameId":"ko","title":"KickOff", imgext:"ko.png"},
//{"provider":"gwt",type:"Table","gameId":"bj21","title":"BlackJack"},
];